services:
  fake-news-api:
    container_name: fake-news-api
    working_dir: /app
    build:
      context: ./fake-news-api
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    command: uvicorn main:app --host "0.0.0.0" --port "8000"

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CLUSTER_ID=default
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_volume:/bitnami/kafka
    ports:
      - 9094:9094

  kafka-ui:
    container_name: kafka-ui
    image: kafbat/kafka-ui:main
    environment:
      KAFKA_CLUSTERS_0_NAME: default
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - 8080:8080
    depends_on:
      - kafka

volumes:
  kafka_volume:
